### ISSUE TITLE
Does this model support fill-in-the-middle?

### ISSUE THREAD

**Issue by HermitSun** [ise-uiuc/magicoder#5]
Fill-in-the-middle can allow the model to make better completions. It would be nice if this model supports it.

**Comment by UniverseFly** [comment]
Hi @HermitSun, our Magicoder-DS models support infilling, since they are fine-tuned from DeepSeek-Coder which supports infilling natively. For example, if you want to do infilling with [Magicoder-S-DS-6.7B](https://huggingface.co/ise-uiuc/Magicoder-S-DS-6.7B), you can refer to [deepseek-coder-6.7b](https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base)'s documentation on infilling and encode your prompt in the same way.

**Comment by erfanium** [comment]
Does this model actually performs better than deepseek-coder-6.7b at fill-in-the-middle tasks? seams fill-in-the-middle is not the goal of this model (although it supported)

**Comment by UniverseFly** [comment]
Hi @erfanium, we found that it could be better at fill-in-the-middle tasks than the base model in some of our follow-up evaluations, but that was small scale and I recommend evaluating both according to your own use cases.
